### ISSUE TITLE
build issue with linux, Ubuntu 22.04.3 LTS 64bit

### ISSUE THREAD

**Issue by minger0** [DSchroer/dslcad#25]
```
testuser@testuser-mycomputer:~/my/code/dslcad$` rustup run stable cargo --version
cargo 1.73.0 (9c4383fb5 2023-08-26)
testuser@testuser-mycomputer:~/my/code/dslcad$ rustup run stable cargo build
    Updating crates.io index
  Downloaded bevy_scene v0.10.1
  Downloaded ab_glyph v0.2.21
  Downloaded bevy_internal v0.10.1
  Downloaded bevy_macro_utils v0.10.1
  Downloaded block v0.1.6
  Downloaded bevy_log v0.10.1
  Downloaded cc v1.0.74
  Downloaded color_quant v1.1.0
  Downloaded cfg_aliases v0.1.1
  Downloaded bevy_render_macros v0.10.1
  Downloaded bevy_core v0.10.1
  Downloaded bevy_utils_proc_macros v0.10.1
  Downloaded beef v0.5.2
  Downloaded bevy_diagnostic v0.10.1
  Downloaded bevy_gilrs v0.10.1
  Downloaded bit-set v0.5.3
  Downloaded bevy_derive v0.10.1
  Downloaded adler v1.0.2
  Downloaded bevy_ecs_macros v0.10.1
  Downloaded bevy_encase_derive v0.10.1
  Downloaded bevy_a11y v0.10.1
  Downloaded bevy_input v0.10.1
  Downloaded logos v0.12.1
  Downloaded bevy_transform v0.10.1
  Downloaded ecolor v0.21.0
  Downloaded encase_derive v0.5.0
  Downloaded bevy_mikktspace v0.10.1
  Downloaded ab_glyph_rasterizer v0.1.8
  Downloaded anstyle-parse v0.2.1
  Downloaded bevy_gltf v0.10.1
  Downloaded bevy_animation v0.10.1
  Downloaded bevy_ptr v0.10.1
  Downloaded bevy_app v0.10.1
  Downloaded async-channel v1.9.0
  Downloaded anstyle v1.0.2
  Downloaded bevy_utils v0.10.1
  Downloaded concurrent-queue v2.2.0
  Downloaded bytemuck_derive v1.4.1
  Downloaded byteorder v1.4.3
  Downloaded com-rs v0.2.1
  Downloaded anstream v0.5.0
  Downloaded bevy_time v0.10.1
  Downloaded approx v0.5.1
  Downloaded async-executor v1.5.1
  Downloaded bevy_winit v0.10.1
  Downloaded parking v2.1.0
  Downloaded overload v0.1.1
  Downloaded num-rational v0.4.1
  Downloaded memoffset v0.6.5
  Downloaded accesskit_winit v0.12.4
  Downloaded cmake v0.1.49
  Downloaded bit-vec v0.6.3
  Downloaded bevy_math v0.10.1
  Downloaded clap_derive v4.4.2
  Downloaded bevy_points v0.2.1
  Downloaded subtle v2.5.0
  Downloaded pp-rs v0.2.1
  Downloaded bevy_tasks v0.10.1
  Downloaded bevy_ui v0.10.1
  Downloaded bevy_text v0.10.1
  Downloaded ahash v0.7.6
  Downloaded grid v0.10.0
  Downloaded bzip2 v0.4.4
  Downloaded bevy_asset v0.10.1
  Downloaded bevy_hierarchy v0.10.1
  Downloaded base64ct v1.6.0
  Downloaded alsa-sys v0.3.1
  Downloaded async-task v4.4.0
  Downloaded accesskit v0.10.1
  Downloaded bevy_polyline v0.6.0
  Downloaded bitflags v2.4.0
  Downloaded sha1 v0.10.5
  Downloaded arboard v3.2.1
  Downloaded bevy_reflect_derive v0.10.1
  Downloaded bevy_window v0.10.1
  Downloaded toml_datetime v0.6.3
  Downloaded strum_macros v0.24.3
  Downloaded clap v4.4.2
  Downloaded base64 v0.13.1
  Downloaded bytemuck v1.13.1
  Downloaded notify v6.1.1
  Downloaded wgpu-types v0.15.2
  Downloaded num-traits v0.2.15
  Downloaded parking_lot_core v0.9.8
  Downloaded addr2line v0.21.0
  Downloaded radsort v0.1.0
  Downloaded ahash v0.8.3
  Downloaded alsa v0.7.1
  Downloaded parking_lot v0.12.1
  Downloaded async-lock v2.8.0
  Downloaded const_panic v0.2.8
  Downloaded codespan-reporting v0.11.1
  Downloaded waker-fn v1.1.0
  Downloaded bevy_sprite v0.10.1
  Downloaded backtrace v0.3.69
  Downloaded arrayvec v0.7.4
  Downloaded bevy_audio v0.10.1
  Downloaded ruzstd v0.2.4
  Downloaded link-cplusplus v1.0.7
  Downloaded tracing-log v0.1.3
  Downloaded bevy_reflect v0.10.1
  Downloaded base64 v0.21.3
  Downloaded bevy_pbr v0.10.1
  Downloaded memchr v2.6.2
  Downloaded bevy_egui v0.20.3
  Downloaded wayland-scanner v0.29.5
  Downloaded colorchoice v1.0.0
  Downloaded num-integer v0.1.45
  Downloaded thiserror v1.0.38
  Downloaded constant_time_eq v0.1.5
  Downloaded cfg-if v1.0.0
  Downloaded aes v0.8.3
  Downloaded bevy_render v0.10.1
  Downloaded smallvec v1.11.0
  Downloaded cxxbridge-macro v1.0.80
  Downloaded ttf-parser v0.19.1
  Downloaded wgpu-hal v0.15.4
  Downloaded widestring v0.5.1
  Downloaded regex v1.9.5
  Downloaded bevy v0.10.1
  Downloaded regex-syntax v0.6.29
  Downloaded equivalent v1.0.1
  Downloaded scopeguard v1.2.0
  Downloaded pin-project-lite v0.2.13
  Downloaded pbkdf2 v0.11.0
  Downloaded password-hash v0.4.2
  Downloaded fixedbitset v0.4.2
  Downloaded hashbrown v0.12.3
  Downloaded ash v0.37.3+1.3.251
  Downloaded euclid v0.22.9
  Downloaded slab v0.4.9
  Downloaded wgpu v0.15.1
  Downloaded downcast-rs v1.2.0
  Downloaded bevy_core_pipeline v0.10.1
  Downloaded erased-serde v0.3.31
  Downloaded strsim v0.10.0
  Downloaded ryu v1.0.15
  Downloaded fxhash v0.2.1
  Downloaded rand_core v0.6.4
  Downloaded pkg-config v0.3.27
  Downloaded x11-dl v2.21.0
  Downloaded serde v1.0.188
  Downloaded version_check v0.9.4
  Downloaded tinyvec_macros v0.1.1
  Downloaded utf8parse v0.2.1
  Downloaded same-file v1.0.6
  Downloaded termcolor v1.1.3
  Downloaded percent-encoding v2.3.0
  Downloaded home v0.5.5
  Downloaded gpu-alloc v0.5.4
  Downloaded taffy v0.3.13
  Downloaded libudev-sys v0.1.4
  Downloaded x11rb v0.10.1
  Downloaded futures-lite v1.13.0
  Downloaded unicode-ident v1.0.5
  Downloaded unicode-bidi v0.3.13
  Downloaded cxx v1.0.80
  Downloaded fastrand v1.9.0
  Downloaded bevy_ecs v0.10.1
  Downloaded gpu-alloc-types v0.2.0
  Downloaded foreign-types-shared v0.1.1
  Downloaded egui v0.21.0
  Downloaded once_cell v1.18.0
  Downloaded cipher v0.4.4
  Downloaded bitflags v1.3.2
  Downloaded anyhow v1.0.75
  Downloaded crossbeam-channel v0.5.8
  Downloaded sysinfo v0.28.4
  Downloaded inflections v1.1.1
  Downloaded fdeflate v0.3.0
  Downloaded event-listener v2.5.3
  Downloaded aho-corasick v1.0.5
  Downloaded petgraph v0.6.4
  Downloaded clap_builder v4.4.2
  Downloaded owned_ttf_parser v0.19.0
  Downloaded dasp_sample v0.11.0
  Downloaded autocfg v1.1.0
  Downloaded rodio v0.17.1
  Downloaded hassle-rs v0.9.0
  Downloaded static_assertions v1.1.0
  Downloaded typenum v1.16.0
  Downloaded getrandom v0.2.10
  Downloaded cpal v0.15.2
  Downloaded tinyvec v1.6.0
  Downloaded regex-automata v0.3.8
  Downloaded block-buffer v0.10.4
  Downloaded renderdoc-sys v0.7.1
  Downloaded time-core v0.1.1
  Downloaded form_urlencoded v1.2.0
  Downloaded url v2.4.1
  Downloaded encase_derive_impl v0.5.0
  Downloaded unicode-normalization v0.1.22
  Downloaded tracing v0.1.37
  Downloaded indexmap v2.0.0
  Downloaded miniz_oxide v0.7.1
  Downloaded generic-array v0.14.7
  Downloaded gethostname v0.2.3
  Downloaded tiff v0.9.0
  Downloaded foreign-types v0.3.2
  Downloaded futures-io v0.3.28
  Downloaded futures-core v0.3.28
  Downloaded fnv v1.0.7
  Downloaded indexmap v1.9.3
  Downloaded deranged v0.3.8
  Downloaded hmac v0.12.1
  Downloaded cpufeatures v0.2.9
  Downloaded heck v0.4.1
  Downloaded zip v0.6.6
  Downloaded hexf-parse v0.2.1
  Downloaded float-cmp v0.9.0
  Downloaded flate2 v1.0.27
  Downloaded itoa v1.0.9
  Downloaded inout v0.1.3
  Downloaded inotify v0.9.6
  Downloaded image v0.24.7
  Downloaded zstd-sys v2.0.8+zstd.1.5.5
  Downloaded idna v0.4.0
  Downloaded strum v0.24.1
  Downloaded cxxbridge-flags v1.0.80
  Downloaded epaint v0.21.0
  Downloaded matchers v0.1.0
  Downloaded gpu-descriptor v0.2.3
  Downloaded digest v0.10.7
  Downloaded zstd v0.11.2+zstd.1.5.2
  Downloaded mio v0.8.8
  Downloaded svg_fmt v0.4.1
  Downloaded log v0.4.20
  Downloaded crypto-common v0.1.6
  Downloaded inotify-sys v0.1.5
  Downloaded filetime v0.2.22
  Downloaded regex-syntax v0.7.5
  Downloaded thread_local v1.1.7
  Downloaded gltf-derive v1.3.0
  Downloaded nohash-hasher v0.2.0
  Downloaded gpu-descriptor-types v0.1.1
  Downloaded simd-adler32 v0.3.7
  Downloaded instant v0.1.12
  Downloaded twox-hash v1.6.3
  Downloaded anstyle-query v1.0.0
  Downloaded scratch v1.0.2
  Downloaded rectangle-pack v0.4.2
  Downloaded clap_lex v0.5.1
  Downloaded encase v0.5.0
  Downloaded sha2 v0.10.7
  Downloaded unicode-xid v0.2.4
  Downloaded lock_api v0.4.10
  Downloaded glyph_brush_layout v0.2.3
  Downloaded ktx2 v0.3.0
  Downloaded thiserror-impl v1.0.38
  Downloaded spirv v0.2.0+1.5.4
  Downloaded libloading v0.7.4
  Downloaded raw-window-handle v0.5.2
  Downloaded hexasphere v8.1.0
  Downloaded guillotiere v0.6.2
  Downloaded emath v0.21.0
  Downloaded profiling v1.0.10
  Downloaded gltf-json v1.3.0
  Downloaded lazy_static v1.4.0
  Downloaded rustversion v1.0.14
  Downloaded walkdir v2.3.3
  Downloaded ogg v0.8.0
  Downloaded rustc-hash v1.1.0
  Downloaded range-alloc v0.1.3
  Downloaded jobserver v0.1.26
  Downloaded unicode-width v0.1.10
  Downloaded stl_io v0.7.0
  Downloaded khronos-egl v4.1.0
  Downloaded zstd-safe v5.0.2+zstd.1.5.2
  Downloaded crc32fast v1.3.2
  Downloaded logos-derive v0.12.1
  Downloaded notify v5.2.0
  Downloaded tracing-attributes v0.1.26
  Downloaded vec_map v0.8.2
  Downloaded nu-ansi-term v0.46.0
  Downloaded quote v1.0.33
  Downloaded sharded-slab v0.1.4
  Downloaded smooth-bevy-cameras v0.8.0
  Downloaded crossbeam-utils v0.8.16
  Downloaded rustc-demangle v0.1.23
  Downloaded gltf v1.3.0
  Downloaded serde_derive v1.0.188
  Downloaded gilrs-core v0.5.7
  Downloaded weezl v0.1.7
  Downloaded webbrowser v0.8.11
  Downloaded proc-macro2 v1.0.66
  Downloaded uuid v1.4.1
  Downloaded tracing-core v0.1.31
  Downloaded slotmap v1.0.6
  Downloaded xml-rs v0.8.16
  Downloaded ron v0.8.1
  Downloaded lewton v0.10.2
  Downloaded gpu-allocator v0.22.0
  Downloaded png v0.17.10
  Downloaded xi-unicode v0.3.0
  Downloaded toml_edit v0.19.14
  Downloaded cxx-build v1.0.80
  Downloaded hashbrown v0.14.0
  Downloaded regex-automata v0.1.10
  Downloaded time v0.3.28
  Downloaded serde_json v1.0.105
  Downloaded gilrs v0.10.2
  Downloaded winnow v0.5.15
  Downloaded glow v0.12.3
  Downloaded quick-xml v0.30.0
  Downloaded tracing-subscriber v0.3.17
  Downloaded syn v1.0.103
  Downloaded wgpu-core v0.15.1
  Downloaded syn v2.0.29
  Downloaded glam v0.23.0
  Downloaded nix v0.26.4
  Downloaded object v0.32.0
  Downloaded gimli v0.28.0
  Downloaded nix v0.24.3
  Downloaded x11rb-protocol v0.10.0
  Downloaded winit v0.28.6
  Downloaded naga v0.11.1
  Downloaded libc v0.2.147
  Downloaded bzip2-sys v0.1.11+1.0.8
  Downloaded jpeg-decoder v0.3.0
  Downloaded 319 crates (23.3 MB) in 3.11s (largest was `tiff` at 1.4 MB)
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.5
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling serde v1.0.188
   Compiling syn v1.0.103
   Compiling once_cell v1.18.0
   Compiling bitflags v1.3.2
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.14.0
   Compiling parking_lot_core v0.9.8
   Compiling lock_api v0.4.10
   Compiling ahash v0.7.6
   Compiling scopeguard v1.2.0
   Compiling thiserror v1.0.38
   Compiling crossbeam-utils v0.8.16
   Compiling memchr v2.6.2
   Compiling quote v1.0.33
   Compiling winnow v0.5.15
   Compiling indexmap v2.0.0
   Compiling log v0.4.20
   Compiling syn v2.0.29
   Compiling toml_datetime v0.6.3
   Compiling pkg-config v0.3.27
   Compiling pin-project-lite v0.2.13
   Compiling fixedbitset v0.4.2
   Compiling getrandom v0.2.10
   Compiling petgraph v0.6.4
   Compiling futures-core v0.3.28
   Compiling tracing-core v0.1.31
   Compiling slab v0.4.9
   Compiling instant v0.1.12
   Compiling event-listener v2.5.3
   Compiling rustc-hash v1.1.0
   Compiling tracing v0.1.37
   Compiling concurrent-queue v2.2.0
   Compiling num-traits v0.2.15
   Compiling waker-fn v1.1.0
   Compiling futures-io v0.3.28
   Compiling fastrand v1.9.0
   Compiling bit-vec v0.6.3
   Compiling toml_edit v0.19.14
   Compiling parking v2.1.0
   Compiling futures-lite v1.13.0
   Compiling bit-set v0.5.3
   Compiling uuid v1.4.1
   Compiling async-lock v2.8.0
   Compiling async-task v4.4.0
   Compiling async-channel v1.9.0
   Compiling thread_local v1.1.7
   Compiling downcast-rs v1.2.0
   Compiling bevy_ptr v0.10.1
   Compiling byteorder v1.4.3
   Compiling async-executor v1.5.1
   Compiling regex-syntax v0.6.29
   Compiling bevy_tasks v0.10.1
   Compiling lazy_static v1.4.0
   Compiling aho-corasick v1.0.5
   Compiling jobserver v0.1.26
   Compiling regex-syntax v0.7.5
   Compiling bevy_macro_utils v0.10.1
   Compiling cc v1.0.74
   Compiling unicode-width v0.1.10
   Compiling termcolor v1.1.3
   Compiling overload v0.1.1
   Compiling nu-ansi-term v0.46.0
   Compiling regex-automata v0.1.10
   Compiling codespan-reporting v0.11.1
   Compiling serde_derive v1.0.188
   Compiling bytemuck_derive v1.4.1
   Compiling regex-automata v0.3.8
   Compiling matchers v0.1.0
   Compiling sharded-slab v0.1.4
   Compiling thiserror-impl v1.0.38
   Compiling bytemuck v1.13.1
   Compiling bevy_utils_proc_macros v0.10.1
   Compiling bevy_reflect_derive v0.10.1
   Compiling bevy_ecs_macros v0.10.1
   Compiling bevy_derive v0.10.1
   Compiling tracing-log v0.1.3
   Compiling mio v0.8.8
   Compiling simd-adler32 v0.3.7
   Compiling crc32fast v1.3.2
   Compiling crossbeam-channel v0.5.8
   Compiling regex v1.9.5
   Compiling adler v1.0.2
   Compiling raw-window-handle v0.5.2
   Compiling miniz_oxide v0.7.1
   Compiling inotify-sys v0.1.5
   Compiling indexmap v1.9.3
   Compiling same-file v1.0.6
   Compiling inotify v0.9.6
   Compiling walkdir v2.3.3
   Compiling filetime v0.2.22
   Compiling flate2 v1.0.27
   Compiling num-integer v0.1.45
   Compiling libloading v0.7.4
   Compiling ash v0.37.3+1.3.251
   Compiling khronos-egl v4.1.0
   Compiling anyhow v1.0.75
   Compiling unicode-xid v0.2.4
   Compiling spirv v0.2.0+1.5.4
   Compiling sysinfo v0.28.4
   Compiling pp-rs v0.2.1
   Compiling num-rational v0.4.1
   Compiling gpu-descriptor-types v0.1.1
   Compiling gpu-alloc-types v0.2.0
   Compiling hexf-parse v0.2.1
   Compiling arrayvec v0.7.4
   Compiling gpu-alloc v0.5.4
   Compiling notify v5.2.0
   Compiling fdeflate v0.3.0
   Compiling encase_derive_impl v0.5.0
   Compiling fxhash v0.2.1
   Compiling wgpu-types v0.15.2
   Compiling profiling v1.0.10
   Compiling renderdoc-sys v0.7.1
   Compiling static_assertions v1.1.0
   Compiling glow v0.12.3
   Compiling png v0.17.10
   Compiling memoffset v0.6.5
   Compiling color_quant v1.1.0
   Compiling image v0.24.7
   Compiling twox-hash v1.6.3
   Compiling encase_derive v0.5.0
   Compiling typenum v1.16.0
   Compiling const_panic v0.2.8
   Compiling ruzstd v0.2.4
   Compiling bevy_encase_derive v0.10.1
   Compiling smallvec v1.11.0
   Compiling hashbrown v0.12.3
   Compiling glam v0.23.0
   Compiling parking_lot v0.12.1
   Compiling erased-serde v0.3.31
   Compiling tracing-subscriber v0.3.17
   Compiling bevy_utils v0.10.1
   Compiling naga v0.11.1
   Compiling gpu-descriptor v0.2.3
   Compiling bevy_render_macros v0.10.1
   Compiling ktx2 v0.3.0
   Compiling generic-array v0.14.7
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling bevy_math v0.10.1
   Compiling bevy_mikktspace v0.10.1
   Compiling bevy_reflect v0.10.1
   Compiling encase v0.5.0
   Compiling hexasphere v8.1.0
   Compiling nix v0.24.3
   Compiling percent-encoding v2.3.0
   Compiling ttf-parser v0.19.1
   Compiling alsa-sys v0.3.1
   Compiling radsort v0.1.0
   Compiling xml-rs v0.8.16
   Compiling ab_glyph_rasterizer v0.1.8
error: failed to run custom build command for `alsa-sys v0.3.1`

Caused by:
  process didn't exit successfully: `/home/testuser/my/code/dslcad/target/debug/build/alsa-sys-57b7fb07bde49b83/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ALSA_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ALSA_STATIC
  cargo:rerun-if-env-changed=ALSA_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/testuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alsa-sys-0.3.1/build.rs:13:18:
  `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "alsa"` did not exit successfully: exit status: 1
  error: could not find system library 'alsa' required by the 'alsa-sys' crate

  --- stderr
  Package alsa was not found in the pkg-config search path.
  Perhaps you should add the directory containing `alsa.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'alsa' found

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
any suggestion on how to proceed?

**Comment by minger0** [comment]
after 
```
sudo apt install libasound2-dev libudev-dev
```
the [opencascade libs](https://techoverflow.net/2022/11/26/how-to-install-opencascade-on-ubuntu-22-04/),
```
sudo apt install -y xfonts-scalable libocct-data-exchange-dev libocct-draw-dev libocct-foundation-dev libocct-modeling-algorithms-dev libocct-modeling-data-dev libocct-ocaf-dev libocct-visualization-dev
```
were needed to be installed
```
$ rustup run stable cargo build
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling opencascade-sys v0.2.0 (https://github.com/bschwind/opencascade-rs?rev=d9391e43bffca1356c1cf74cd15837f2ceb6286e#d9391e43)
error: failed to run custom build command for `opencascade-sys v0.2.0 (https://github.com/bschwind/opencascade-rs?rev=d9391e43bffca1356c1cf74cd15837f2ceb6286e#d9391e43)`

Caused by:
  process didn't exit successfully: `/home/testuser/my/code/dslcad/target/debug/build/opencascade-sys-50caed4f7197da8d/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/testuser/my/code/dslcad/target/debug/build/opencascade-sys-54e19048fb829fa7/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/testuser/.cargo/git/checkouts/opencascade-rs-56632466c8b8dee3/d9391e4/crates/opencascade-sys/OCCT" "-DCMAKE_INSTALL_PREFIX=/home/testuser/my/code/dslcad/target/debug/build/opencascade-sys-54e19048fb829fa7/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring incomplete, errors occurred!
  See also "/home/testuser/my/code/dslcad/target/debug/build/opencascade-sys-54e19048fb829fa7/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at CMakeLists.txt:3 (find_package):
    By not providing "FindOpenCASCADE.cmake" in CMAKE_MODULE_PATH this project
    has asked CMake to find a package configuration file provided by
    "OpenCASCADE", but CMake did not find one.

    Could not find a package configuration file provided by "OpenCASCADE" with
    any of the following names:

      OpenCASCADEConfig.cmake
      opencascade-config.cmake

    Add the installation prefix of "OpenCASCADE" to CMAKE_PREFIX_PATH or set
    "OpenCASCADE_DIR" to a directory containing one of the above files.  If
    "OpenCASCADE" provides a separate development package or SDK, be sure it
    has been installed.


  thread 'main' panicked at /home/testuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.49/src/lib.rs:1104:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at /home/testuser/.cargo/git/checkouts/opencascade-rs-56632466c8b8dee3/d9391e4/crates/opencascade-sys/build.rs:92:23:
  Pre-installed OpenCASCADE library not found. You can use `builtin` feature if you do not want to install OCCT libraries system-wide.: Any { .. }
warning: build failed, waiting for other jobs to finish...
```
pls help me to get the build running

**Comment by DSchroer** [comment]
Hey. Sorry about the late reply. Try compiling with `-F builtin-occt` its a flag that should build opencascade with the application. If not you need to clone the OCCT repo and manually build it with the following config:
```
cmake \
    -DBUILD_LIBRARY_TYPE=Static \
    -DBUILD_MODULE_ApplicationFramework=FALSE \
    -DBUILD_MODULE_Draw=FALSE \
    -DUSE_D3D=FALSE \
    -DUSE_DRACO=FALSE \
    -DUSE_EIGEN=FALSE \
    -DUSE_FFMPEG=FALSE \
    -DUSE_FREEIMAGE=FALSE \
    -DUSE_FREETYPE=FALSE \
    -DUSE_GLES2=FALSE \
    -DUSE_OPENGL=FALSE \
    -DUSE_OPENVR=FALSE \
    -DUSE_RAPIDJSON=FALSE \
    -DUSE_TBB=FALSE \
    -DUSE_TCL=FALSE \
    -DUSE_TK=FALSE \
    -DUSE_VTK=FALSE \
    -DUSE_XLIB=FALSE \
    -DBUILD_MODULE_DETools=FALSE
```
Its not a very smooth setup right now.

**Comment by DSchroer** [comment]
I have improved the build process. There is now a justfile that acts as a build script to setup OCCT. Full build should work by running:
```
just build
```

It takes care of pre-building OCCT the first time and uses the correct env variables.
